# Generated by Django 5.2.4 on 2025-07-06 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='entrada_disponible',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='entrada_precio',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='segundo',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='segundo_disponible',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='segundo_precio',
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='restaurants.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Segundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundos', to='restaurants.menu')),
            ],
        ),
    ]
