# Generated by Django 5.2.4 on 2025-07-06 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_menu_entrada_remove_menu_entrada_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.entrada'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='segundo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.segundo'),
        ),
    ]
