# Generated by Django 5.2.1 on 2025-07-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_pedido_entrada_alter_pedido_segundo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='segundo',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='segundo',
            name='menu',
        ),
        migrations.AddField(
            model_name='entrada',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entrada',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='entradas/'),
        ),
        migrations.AddField(
            model_name='segundo',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='segundo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='segundos/'),
        ),
    ]
