# Generated by Django 5.2.4 on 2025-07-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('restaurante', 'Restaurante')], default='cliente', max_length=15),
        ),
    ]
