services:
  - type: web
    name: django-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: resto_db_render
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
